CREATE TABLE cards (
  id VARCHAR(100) PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  description TEXT,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kegs (
    id SERIAL PRIMARY KEY,
    volume NUMERIC(7,2) DEFAULT 30000.00,
    store_price NUMERIC(6,2) DEFAULT 1022.90,
    ml_price NUMERIC(5,4) DEFAULT 0.0400,
    pant NUMERIC(6,2) DEFAULT 625.00,
    beer VARCHAR(100) DEFAULT 'JEVER',
    description TEXT,
    status VARCHAR(16) DEFAULT 'NOT OPENED YET',
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pours (
  id SERIAL PRIMARY KEY,
  volume NUMERIC(6,2) DEFAULT 0.00,
  cost NUMERIC(6,2),
  user_id INTEGER REFERENCES users(id),
  card_id VARCHAR(100) REFERENCES cards(id),
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
